### ISSUE TITLE
Shasum files

### ISSUE THREAD

**Issue by jbouter** [roaldnefs/messagebird_exporter#1]
Kindly supply `sha256sums.txt` files with the releases, which makes verification of the downloaded archives easier during automated installation.  See [node_exporter](https://github.com/prometheus/node_exporter/releases/tag/v1.0.1) releases as an example.

**Comment by roaldnefs** [comment]
I've moved the CI pipeline from Travis to GitHub Action and implemented **goreleaser**. Besides adding the checksums, this also allows building `*.deb` and `*.rpm` files, see: https://github.com/roaldnefs/messagebird_exporter/releases/tag/v0.1.0
